Adding wildcard suffix to SCVBYOATenantStack under CloudformationAccess Sid
service-cloud-voice/examples-from-doc pull request #64
Opened 2024-02-13 09:20 UTC by arijit725

Adding wildcard suffix to SCVBYOATenantStack under CloudformationAccess Sid

2024-02-13 18:01 UTC, jinalkathiara commented
Can you update your comment and PR commit message to reflect that this change is required for the contact center 14.1 onwards ?

2024-02-13 18:01 UTC, jinalkathiara requested changes

2024-02-13 18:01 UTC, jinalkathiara commented on iam_policies/SCVProvisioningPolicy.json
> +                "arn:aws:cloudformation:*:<AWS_ACCOUNT_ID>:stack/SCVBYOATenantStack*/*",
Update PR Commit message

2024-02-14 04:08 UTC, arijit725 commented on iam_policies/SCVProvisioningPolicy.json
> +                "arn:aws:cloudformation:*:<AWS_ACCOUNT_ID>:stack/SCVBYOATenantStack*/*",
There is already commit message present. Please let me know if anything specific need to be included.

2024-02-14 04:43 UTC, jinalkathiara approved these changes

2024-02-14 04:43 UTC, jinalkathiara commented on iam_policies/SCVProvisioningPolicy.json
> +                "arn:aws:cloudformation:*:<AWS_ACCOUNT_ID>:stack/SCVBYOATenantStack*/*",
Can you add commit message for the open source friendly language. "Updating Contact Center with 14.1 provisioning role"

2024-02-14 04:44 UTC, merged