Restrict log access for SCVProvisioningPolicy
service-cloud-voice/examples-from-doc pull request #71
Opened 2024-06-21 11:06 UTC by archana1296

Restrict log access for SCVProvisioningPolicy

2024-06-21 16:09 UTC, jinalkathiara requested changes

2024-06-21 16:09 UTC, jinalkathiara commented on iam_policies/SCVProvisioningPolicy.json
> +        {
@archana1296 Why is this log group access required ? 
scvbyoaaccesscloudwatchloggroup, who is creating this loggroup ?

2024-06-24 04:45 UTC, archana1296 commented on iam_policies/SCVProvisioningPolicy.json
> +        {
The SCVProvisioningRole is creating this log group. Without adding this we are getting the error:

User: arn:aws:sts::851725360410:assumed-role/SCVProvisioningPolicy/AWSCloudFormation is not...logs:CreateLogGroup on resource: arn:aws:logs:us-east-1:851725360410:log-group:scvbyoaaccesscloudwatchloggroup:log-stream: because no identity-based policy allows the logs:CreateLogGroup action 

That's why we have added this.

2024-06-25 16:14 UTC, jinalkathiara commented on iam_policies/SCVProvisioningPolicy.json
> +        {
Can we sync up on this topic @arijit725 ?

2024-06-26 04:16 UTC, jinalkathiara approved these changes

2024-06-26 04:16 UTC, merged